# Generated by Django 5.0.3 on 2024-03-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoencarrito',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='productoencarrito',
            name='nombre',
        ),
        migrations.AddField(
            model_name='productoencarrito',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.producto'),
            preserve_default=False,
        ),
    ]
